#[repr(u8)]
#[derive(Debug)]
pub enum OpCode {
    Push = 0x01,
    Pop = 0x02,
    Add = 0x03,
    Sub = 0x04,
    Mul = 0x05,
    Div = 0x06,
    Equal = 0x07,
    Greater = 0x08,
    GreaterEqual = 0x09,
    Less = 0x0A,
    LessEqual = 0x0B,
    Call = 0x0C,
    Index = 0x0D,
    Jmp = 0x0E,
    JmpFalse = 0x0F,
    JmpTrue = 0x10,
    Nop = 0x11,
    LoadCaptured = 0x12,
    LoadLocal = 0x13,
    LoadMember = 0x14,
    StoreCaptured = 0x15,
    StoreLocal = 0x16,
    MakeList = 0x17,
    Not = 0x18,
    Plus = 0x19,
    Minus = 0x1A,
    Return = 0x1B,
    VReturn = 0x1C,
    LoadGlobal = 0x1D,
    StoreGlobal = 0x1E,
}

impl OpCode {
    pub fn from(code: u8) -> Option<OpCode> {
        match code {
            0x01 => Some(OpCode::Push),
            0x02 => Some(OpCode::Pop),
            0x03 => Some(OpCode::Add),
            0x04 => Some(OpCode::Sub),
            0x05 => Some(OpCode::Mul),
            0x06 => Some(OpCode::Div),
            0x07 => Some(OpCode::Equal),
            0x08 => Some(OpCode::Greater),
            0x09 => Some(OpCode::GreaterEqual),
            0x0A => Some(OpCode::Less),
            0x0B => Some(OpCode::LessEqual),
            0x0C => Some(OpCode::Call),
            0x0D => Some(OpCode::Index),
            0x0E => Some(OpCode::Jmp),
            0x0F => Some(OpCode::JmpFalse),
            0x10 => Some(OpCode::JmpTrue),
            0x11 => Some(OpCode::Nop),
            0x12 => Some(OpCode::LoadCaptured),
            0x13 => Some(OpCode::LoadLocal),
            0x14 => Some(OpCode::LoadMember),
            0x15 => Some(OpCode::StoreCaptured),
            0x16 => Some(OpCode::StoreLocal),
            0x17 => Some(OpCode::MakeList),
            0x18 => Some(OpCode::Not),
            0x19 => Some(OpCode::Plus),
            0x1A => Some(OpCode::Minus),
            0x1B => Some(OpCode::Return),
            0x1C => Some(OpCode::VReturn),
            0x1D => Some(OpCode::LoadGlobal),
            0x1E => Some(OpCode::StoreGlobal),
            _ => None,
        }
    }
    
    pub fn get_operand_size(&self) -> u32 {
        match self {
            OpCode::Push => 0x02,
            OpCode::Pop => 0x00,
            OpCode::Add => 0x00,
            OpCode::Sub => 0x00,
            OpCode::Mul => 0x00,
            OpCode::Div => 0x00,
            OpCode::Equal => 0x00,
            OpCode::Greater => 0x00,
            OpCode::GreaterEqual => 0x00,
            OpCode::Less => 0x00,
            OpCode::LessEqual => 0x00,
            OpCode::Call => 0x00,
            OpCode::Index => 0x00,
            OpCode::Jmp => 0x04,
            OpCode::JmpFalse => 0x04,
            OpCode::JmpTrue => 0x04,
            OpCode::Nop => 0x00,
            OpCode::LoadCaptured => 0x04,
            OpCode::LoadLocal => 0x02,
            OpCode::LoadMember => 0x02,
            OpCode::StoreCaptured => 0x04,
            OpCode::StoreLocal => 0x02,
            OpCode::MakeList => 0x04,
            OpCode::Not => 0x00,
            OpCode::Plus => 0x00,
            OpCode::Minus => 0x00,
            OpCode::Return => 0x00,
            OpCode::VReturn => 0x00,
            OpCode::LoadGlobal => 0x02,
            OpCode::StoreGlobal => 0x02,
        }
    }
}
